### ISSUE TITLE
Dataset title

### ISSUE THREAD

**Issue by damianooldoni** [riparias/union-list#11]
This issue is in some way linked to #2. 
At the moment we name this checklist as "List of Invasive Alien Species of Union concern". However, this could be a source of concerns with EU. Maybe can we add the "LIFE RIPARIAS" prefix? Any idea?

**Comment by timadriaens** [comment]
I see your point, but it is not only the "RIPARIAS Union List", it is one we used at INBO for baseline reporting, for TrIAS indicators, for EU reporting etc. And essentially that is just what it is. So I would just leave that title as is and make sure the metadata explain that this is our work and our interpretation of mapping the Union list taxonomy to the GBIF backbone.

**Comment by damianooldoni** [comment]
Agree.
