### ISSUE TITLE
Publication union list on IPT/GBIF

### ISSUE THREAD

**Issue by damianooldoni** [riparias/union-list#16]
The data in [`./data/processed`](https://github.com/riparias/union-list/tree/main/data/processed) and the [metadata](https://docs.google.com/document/d/1VDxqzyQxMsEF3kZDu9WSRAwuB2PnkG03AOd745cN8_Y/edit) are ready for publication on INBO's IPT.

**Comment by LienReyserhove** [comment]
Dataset published, please upload the DOI in the dataset so I can upload it again with the DOI :-) 
https://doi.org/10.15468/97aucj

**Comment by damianooldoni** [comment]
Thanks @LienReyserhove! Great news 🥳  I have just uploaded the DOI both in README and Rmd mapping. Green light for (re)publication.

**Comment by LienReyserhove** [comment]
Done!

**Comment by damianooldoni** [comment]
Indeed, I confirm this. Thanks again! 👏
