### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by damianooldoni** [riparias/union-list#2]
@timadriaens: @peterdesmet and I are wondering who should be the author of this checklist on GBIF. 
For sure, we three, but the main source of information comes from EU. Should we include it? If yes, how?

**Comment by timadriaens** [comment]
I had the same thoughts, it would be better if someone at the JRC would actually author it, provided they can also maintain it.

**Comment by timadriaens** [comment]
I propose to ask Ana-Cristina Cardoso what she thinks

**Comment by damianooldoni** [comment]
About maintenance (mapping to Dwc, pulication), we can do it at first stage if they do not have the know how to do it themselves.

**Comment by peterdesmet** [comment]
I think it is unlikely they will ever take over maintenance. But we should still ask about authors. And we should be added as co-authors, since we did the transformation work.

**Comment by damianooldoni** [comment]
Hi @timadriaens, could you please give me an update about this? We need to have this checklist on GBIF, that's sure. We get data from EASIN (#6) as they suggested to us and we are happy about it. How to proceed then?

**Comment by timadriaens** [comment]
This is what we asked:

Dear xxx,
(cc Oscibio colleagues)

Hope you are well. I would like to get your advice on something. Within the framework of the Life [RIPARIAS](https://www.riparias.be/) project we want to rapidly publish the Union List as a species checklist on GBIF (github issue [here](https://github.com/riparias/union-list)). We are actually ready to push the publication button and would need that relatively fast as we will use it in our dataflows and early warning & management registration system currently under development. 

Having the list on gbif will greatly facilitate exercises that involve bringing together data from various sources and data extractions from GBIF (e.g. also for baseline reporting). We performed the mapping of the consolidated version of the Union List to Darwin Core standard (carefully dealing with synonyms etc.) and also described the metadata. I can also see other benefits e.g. appearance on the Union List of IAS could be flagged in GBIF (cf. the GRIIS checklists).

However, we do feel it is not entirely appropriate to assign ourselves as authors of such a checklist which is actually a policy instrument. Would you have any thoughts on how to deal with this? Maybe it would be more appropriate if the list were effectively authored by "European Commission", and perhaps it could be with us and with the JRC to supervise, update and maintain that checklist when it is updated (not that we want to give you more work of course, we can provide any tech support you need on dealing with DwC mapping and repeatable dataflows)? Related to that is the question which license we have to choose, we feel CC0 is probably appropriate for something that is bound to a public legal document but maybe you have other thoughts. As we need to proceed with RIPARIAS developments, we can for now publish it under our names and can always change that afterwards.

Actually, it is a pertinent question for many policy lists e.g. the Habitat Directive annexes could also find their way to gbif which raises the concern who should author and curate it. Do you have any ideas? Should I take this up with Juan or the EC IAS team?

---------------------------------------------------
Here is the response we got from EASIN

Dear xxxx,

Thank you for consulting us on this issue.

As you know the IAS of Union concern are already included in EASIN, acting as the official information system in Art. 25 of the EU Regulation 1143/2014, and searchable through a specific filter.

The list can be used to check for spatial data available in the EASIN geodatabase, gathered from literature, EASIN data partners and Members States Competent Authorities involved in the implementation of the EU Regulation on IAS. The latter include also the data officially notified by MSs authorities via EASIN-NOTSYS (Art. 15, 16, 17).

EASIN overarching goal is to improve the scientific data informing the implementation of the EU Regulation 1143/2014.

In this context, we would be like a to talk with you for understanding the RIPARIAS dataflows and the early warning & management systems, and the advantages for the project in having a checklist on IAS of Union concern in GBIF.

We have considered your question about the publication of the checklist in GBIF, how to acknowledge the authors and under which license to release it. We could offer to publish, update and maintain it as a data set in the [JRC Data Catalogue](https://priv-bx-myremote.tech.ec.europa.eu/,DanaInfo=.adbvdDoxjHnmKq7535rRxC,SSL+), with reference to the Commission Implementing Regulations, and licensed under CC0.

**It could also be published in GBIF, with the same acknowledgment and  license, but we will not take the responsibility for its update and maintenance.**

With best regards,
xxxx
Scientific Officer
European Commission
Joint Research Centre
Directorate D – Sustainable Resources

**Comment by timadriaens** [comment]
We have to acknowledge that we dit not react to their request for more information. Anyway, if they release it under CC0 then that's covered, and I feel we did explain it already in the email.

I think we could start from the list we have used for many applications i.e. the **[eu_concern_species.tsv](https://github.com/trias-project/indicators/blob/main/data/input/eu_concern_species.tsv)**

There is I think no problem if we just publish that ourselves under our names (unfortunately, GBIF do not allow generic author names cf. RIPARIAS (2023)...) but we can specify this in the metadata, right?

Where we could really give some added value (and could also kind of justify that this is "our" "RIPARIAS" interpretation of the Union List, is to add all relevant GBIF keys that we need (from a Belgian perspective), to harvest all the necessary data for instance for early warning. We know the problems well by now with synonymy, subspecies, species that are under different keys in different databases etc. This is done nowhere in EASIN whereas it is actually super necessary (for instance, for Member State baseline reporting), so I think that information would also interest them.

The workflow could be that we use our list, add the necessary keys, and enrich this with what we can harvest (and find useful for the project) through the EASIN api.

I think we then need to inform EASIN and leave an opening for them to be involved.

**Comment by timadriaens** [comment]
happy to discuss field we need

**Comment by timadriaens** [comment]
after a discussion with @damianooldoni we decided to publish our list first, and then to approach EASIN to ask if they would like to co-author the dataset and to discuss any issues with taxonomy or enrichment of the dataset through their api.
