### ISSUE TITLE
License

### ISSUE THREAD

**Issue by damianooldoni** [riparias/union-list#3]
Which license should we apply to this checklist? CC0?
This issue is of course linked to #2.

**Comment by peterdesmet** [comment]
Related to #2 indeed and to be asked by original authors.

**Comment by timadriaens** [comment]
indeed think CC0 should apply but I will ask this in my email to the JRC

**Comment by damianooldoni** [comment]
Decided to publish ouw "own" version of the list on GBIF, so CC0 will be.
